/**
 * Add here your GitHub username and message.
 *
 * Add it at the end, after the last contributor.
 *
 * Format:
 * { username: 'your-username', message: 'Say something kind or fun' },
 *
 * The message must be short and respect our code of conduct.
 */
var contributors = [
  { username: 'Kazeno21', message: 'Happy Hacktoberfest 2020:)' },
  { username: 'David-Lazaro-Fernandez', message: 'Ducky DucktoberFest 2020!!' },
  { username: 'bpetetot', message: 'Happy Hacktoberfest 2020!' },
  { username: 'tk021', message: 'What do ducks like to eat with soup? Quackers.' },
  { username: 'callmebhawesh', message: 'This really awesome, Happy Hacktoberfest 2020!' },
  { username: 'brunosabot', message: 'Hello, Hacktoberfest :)' },
  { username: 'Riya-code', message: 'Happy Hacking!' },
  { username: 'nikhilomkar99', message: 'Added a duck.Happy Hacktoberfest 2020!' },
  { username: 'SushanShakya', message: 'Would you like some tea too ??' },
  { username: 'anishghimire603', message: 'Have fun and contribute to Open Sources.' },
  { username: 'bytesagar', message: 'Commit message not crime😁😉' },
  { username: 'lapalb', message: 'Be curious. Read widely. Try new things. What people call intelligence just boils down to curiosity.' },
  { username: 'Kacimi-Amine', message: 'Happy Hacktoberfest 2020!' },
  { username: 'murilopereirame', message: 'Stay Home! Stop spreading COVID-19! You are not alone :) Happy hacking!' },
  { username: 'defuex', message: 'Austrias Next Ducky 2020!' },
  { username: 'ashiishme', message: 'Stay safe, God bless all.' },
  { username: 'premkiran7', message: 'Hacktoberfest is cool' },
  { username: 't6tg', message: 'Happy Hacktoberfest 2020! 🐣' },
  { username: 'lvmenezes', message: 'Show must code on' },
  { username: 'paddlepop25', message: 'This is my first PR! Wheeee!' },
  { username: 'srishtipoudel', message: 'Stay Safe, Stay Negative'},
  {
    username: 'Natasha1305',
    message: 'This was a great first experience. Thank You!',
  },
  { username: 'R-Jin', message: 'Happy Hacktober 2020 :)' },
  { username: 'Capt-Titanium', message: 'Duck to win!' },
  {
    username: 'Huzaifaahmed20',
    message: 'I have added my cool duck on this repo.',
  },
  {
    username: 'AjayThakur12',
    message: 'First time Hacktoberfest feeling Awesome',
  },
  { username: 'SinghCoder', message: 'Hola!! Happy Hacktoverfest!!' },
  { username: 'alanlengkoan', message: 'Happy Hacking 2020 from Indonesia!' },
  {
    username: 'renanlmiranda',
    message: 'There is no advantage to living life on the run.',
  },
  {
    username: 'ukt1997',
    message: 'My 1st Contribution to Open Source , Happy Hacktoberfest 2020!',
  },
  {
    username: 'MikeLikesCode',
    message: 'I love my duck so much! Happy Hacktoberfest!',
  },
  { username: 'Ranjeeta01', message: 'Stay calm and code!' },
  {
    username: 'kchatr',
    message: "Here's to my first ever Hacktoberfest contribution :D",
  },
  { username: 'AnggaR96s', message: 'Enjoy #Hacktoberfest2020!' },
  { username: 'Edward2206', message: 'Happy Hacktoberfest 2020!' },
  { username: 'Callmegoodwater', message: 'Ben you are a crazy guy !!! #hacktoberfest' },
  { username: 'zesterquinn', message: 'Quaktoberfest 2020!' },
  { username: 'nagahshi', message: 'QUACK! #hacktoberfest' },
  { username: 'beforesecond', message: 'Happy Hacking ! #hacktoberfest' },
  { username: 'colabottles', message: 'Hey yo! Happy Hacktoberfest 2020!' },
  { username: 'mukesh2309', message: 'word hard' },
  { username: 'amimaro', message: 'llllllllllllllljjjjjjnnnnnncccceeeee sorry, it was my cat!' },
  {
    username: 'idm1303',
    message: 'Quack!! Quack quack.. quaaaack.. quackquackquaackk!!'
  },
  { username: 'Saral33', message: 'Keep coding :)' },
  { username: 'weiyi-m', message: 'happy hacktoberfest!' },
  { username: 'mendelevium28', message: 'Quack me up!' },
  { username: 'JoseRivera12', message: 'Happy coding ;)' },
  { username: 'nikki156', message: 'Happy Hacktoberfest 2020!' },
  { username: 'Ryzenv9', message: 'Ryan was here. #Hacktoberfest2020;)' },
  { username: 'loic5', message: 'Happy #Hacktoberfest2020!!!!!!!!!!!' },
  { username: 'jeanphibaconnais', message: 'Enjoy Hacktoberfest2020 ! 🤘' },
  { username: 'jlandure', message: '🎉 Happy Hacking 2020! 💚' },
  { username: 'JoseRivera12', message: 'Happy coding ;)' },
  { username: 'Tazminia', message: 'Free PR for everyone' },
  { username: 'chocho01', message: '❤️🦆 & ❤️ Hacktoberfest' },
  { username: 'JoseRivera12', message: 'Happy coding ;)' },
  { username: 'jbleduigou', message: 'Hello, Gophers!' },
  { username: "Fabianolvs", message: "Get away from js kids! Just kiding! XD" },
  { username: "werikgpaula", message: "🦆 Bee free" },
  { username: "Nick448", message: "Hey you!!!" },
  { username: "sarthakregmi", message: "Hippie detective" },
  { username: 'Marcelinoderry', message: 'Happy Hacktoberfest 2020 #popo[L]' },
  { username: 'LNCH', message: 'Darth Ducky shall take over the world!' },
  { username: "mateahoward", message: "Happy Coding 💚" },
  { username: 'cleisoncarlos', message: '🦆 Happy Quacktoberfest 2020!' },
  { username: 'mayie', message: "❤️🦆" },
  { username: "Romakita", message: "Happy QUACK #Hacktoberfest2020 😉" },
  { username: "manuarlin", message: "Wonderful way to discover open source! Go ducks!" },
  { username: "mt-evarest", message: "Happy Quacking!" },
  { username: "sj056", message: "hacktoberfest 2020!!" },
  { username: 'JacobGeoGeek', message: 'Hello/Bonjour from Canada ! To all the devs in this world: Happy Hacktoberfest 2020 to everyone 🎉🎉' },
];
