# Compress images on demand (workflow_dispatch), and at 11pm every Sunday (schedule).
# Open a pull request if any images can be compressed
name: Images
on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * 0'
jobs:
  build:
    name: Optimize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Resize images
        uses: xprilion/img-resizer-inplace@v1
        with:
          target: ducks
          dimensions: 300x300
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          pngQuality: '95'
      - name: Create New Pull Request If Needed
        uses: peter-evans/create-pull-request@master
        with:
          title: Compressed Images Nightly
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}